sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - rm ~/.m2/settings.xml
script:
  - mvn -f src/pom.xml -B -U -T1C -fae -Prelease clean install && mvn -f src/community/pom.xml -B -U -T2 -fae -DskipTests -Prelease -PcommunityRelease clean install
notifications:
  email:
    on_success: never
    on_failure: never
jdk: oraclejdk8
