name: PostGIS app-schema online tests

on: [ pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  appschema-postgis:

    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis:15-3.4
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: geoserver
          POSTGRES_USER: geoserver
          POSTGRES_DB: appschema
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - uses: actions/checkout@v2
      - name: Maven repository caching
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: gs-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            gs-${{ runner.os }}-maven-
      - name: Build GeoServer dependent modules (no tests, prepare fresh artifacts)
        run: mvn -B clean install -T2 -U --file src/pom.xml -Prelease,app-schema-online-test -DskipTests -pl :gs-app-schema-postgis-test -am -Dspotless.apply.skip=true
      - name: Build PostGIS app-schema online tests
        run: |
          mkdir ~/.geoserver
          cat <<EOT >>   ~/.geoserver/postgis.properties
          user=geoserver
          port=5432
          password=geoserver
          passwd=geoserver
          url=jdbc\:postgresql\://localhost/appschema
          host=localhost
          database=appschema
          driver=org.postgresql.Driver
          EOT
          mvn -B clean install -nsu --file src/pom.xml -Prelease,app-schema-online-test -pl :gs-app-schema-postgis-test -Dspotless.apply.skip=true
      - name: Remove SNAPSHOT jars from repository
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {} 
